### ISSUE TITLE
Taking over project maintainance / PyPI name?

### ISSUE THREAD

**Issue by pradyunsg** [nandoflorestan/releaser#1]
Hi @nandoflorestan!

I've been working on automating the release processes of a few Python packages that I maintain (like [pip](https://github.com/pypa/pip/blob/master/noxfile.py#L153), [packaging](https://github.com/pypa/packaging/issues/253) and [vendoring](https://github.com/pradyunsg/vendoring/blob/master/noxfile.py#L103)).  Over the course of this exercise, I've gained a decent amount of understanding, of what could be a good design for a release-oriented automation tool. I started working on writing such a tool and thought that `releaser` would be a great name for it.

I found this package is uploaded to PyPI under that name, but seems like it isn't being worked on anymore. It's even fairly similar in spirit, to what I'm thinking of. :)

---

Would you be willing to transfer ownership of the PyPI name `releaser`, by adding me (`pradyunsg` on PyPI) as an "Owner"?

**Comment by nandoflorestan** [comment]
What is missing from my releaser, that yours would get?
What are the features I currently have, that you would drop?
Please tell us more about your vision for the project.
Then if you have time, tell us if there's anything bad you see in the current code, please.

**Comment by nandoflorestan** [comment]
Closing due to more than 1.5 months of inactivity on the part of the requester.
