### ISSUE TITLE
Release new version to PyPI?

### ISSUE THREAD

**Issue by ulygit** [nandoflorestan/releaser#2]
The latest version of 'releaser' in PyPI is broken on upgrading to Python3. It appears you're most recent push to master addresses the problem I'm seeing, but it's not been released to PyPI. I will sidestep the obvious irony of this situation, and request that you push so we can all bask in your improvement.

As a token of my appreciation, I am starring your project now. Thank you!

N.B. I looked for a way to flag the project as "out of date" from within PyPI, but I couldn't find it.

**Comment by nandoflorestan** [comment]
Okay, one less reason for irony in this world!  Please realise, Releaser 1.3 got released (with releaser).

Such a release.
